# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - az204att01(dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8bda630bfc9d41608722e4f422760f62 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ce003db24884c6bbeb63d2691d9f278 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8bda630bfc9d41608722e4f422760f62 }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'az204att01'
        slot-name: 'dev'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_45d08305849f447f84a26f8c14e12f02 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8bda630bfc9d41608722e4f422760f62 }}/nginx:${{ github.sha }}'